[project]
name = "fantasy-volley"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sympy",
    "numpy",
    "gradio>=5.22.0",
    "matplotlib>=3.10.1",
    "plotly>=6.0.1",
]
